apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weather-microservice-pod
  namespace: default
spec:
  interval: 5m   # Specify the reconciliation interval (e.g., every 5 minutes)
  releaseName: weather-microservice-pod
  chart:
    spec:
      chart: ./weather-microservice-helm
      version: 0.1.0
      sourceRef:
        kind: GitRepository
        name: weather-microservice-helm
        namespace: default
  values:
    replicaCount: 2
    image:
      repository: apurvvaish/weather-forecast
      pullPolicy: IfNotPresent
      tag: "latest"
